language: ruby
cache: bundler
before_install: gem update bundler
rvm:
  - 2.1
  - 2.2
  - 2.3.1
  - 2.4.1
gemfile:
  - gemfiles/jekyll_3.5.gemfile
  - gemfiles/jekyll_3.4.gemfile
  - gemfiles/jekyll_3.3.gemfile
  - gemfiles/jekyll_3.2.gemfile
  - gemfiles/jekyll_3.1.gemfile
  - gemfiles/jekyll_3.gemfile
after_success:
  - bundle exec codeclimate-test-reporter
addons:
  code_climate:
    repo_token: 03d64532821ff06fd0cf9ae57dacc81b2322ac37ed14c5cfbb90ffea40e9c7fb
