language: ruby
cache: bundler
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.1
  - 2.4.0
gemfile:
  - gemfiles/jekyll_3.3.gemfile
  - gemfiles/jekyll_3.2.gemfile
  - gemfiles/jekyll_3.1.gemfile
  - gemfiles/jekyll_3.gemfile
before_install: gem update bundler
