name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        ruby: ['2.6', '2.7', '3.0', '3.1']
        gemfile:
          - gemfiles/jekyll_3.8.gemfile
          - gemfiles/jekyll_3.7.gemfile
          - gemfiles/jekyll_3.6.gemfile
          - gemfiles/jekyll_3.5.gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run Test
      run: bundle exec rake
