name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        ruby: ['2.7', '3.0', '3.1', '3.2', '3.3']
        gemfile:
          - gemfiles/jekyll_3.9.gemfile
          - gemfiles/jekyll_4.0.gemfile
          - gemfiles/jekyll_4.1.gemfile
          - gemfiles/jekyll_4.2.gemfile
          - gemfiles/jekyll_4.3.gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run Test
      run: bundle exec rake

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true
      - uses: paambaati/codeclimate-action@v6.0.0
        env:
          CC_TEST_REPORTER_ID: 03d64532821ff06fd0cf9ae57dacc81b2322ac37ed14c5cfbb90ffea40e9c7fb
        with:
          coverageCommand: bundle exec rake
